version: '2'
services:
  nodered:
    image: peteanusergiu/nodered
    ports:
      - "1880:1880"
    volumes:
      - "/data"
    environment:
      FLOWS: myFlows.json
#NODE_OPTIONS: "--max_old_space_size=128"
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "/data/db"
    restart: always
  rabbitmq:
#    image: rabbitmq
    image: rabbitmq:3-management # management plugin installed and enabled by default
    environment:
       - RABBITMQ_DEFAULT_VHOST=asDocument-rabbitmq
       - RABBITMQ_DEFAULT_USER=drusername
       - RABBITMQ_DEFAULT_PASS=drpassword
    hostname: asDocument-rabbitmq
    ports:
      - 5672:5672 # port for the daemon API, can be exposed to public
      - 15672:15672  # port for the Management interface
    restart: always
    volumes:
      - "/var/lib/rabbitmq"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - "/data"
  freeboard:
    #build: ./freeboard/
    image: peteanusergiu/freeboard
    ports:
      - "82:82"
    volumes:
      - "/data"
    