version: '2'
services:
  mongodb:
    image: mongo
    ports:
        - "27017:27017" 
  mongodata:
    image: ubuntu
    volumes:
      - "/persistence/mongodb:/data/db"
    command: echo Persistence for Mongo